"""Vimdoc: Vim helpfile generation."""

SECTION = 'SECTION'
BACKMATTER = 'BACKMATTER'
EXCEPTION = 'EXCEPTION'
DICTIONARY = 'DICTIONARY'
FUNCTION = 'FUNCTION'
COMMAND = 'COMMAND'
SETTING = 'SETTING'
FLAG = 'FLAG'
